# Generated by Django 2.0.6 on 2018-06-09 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='data',
            new_name='date',
        ),
    ]
