# Generated by Django 2.0.6 on 2018-06-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180616_0723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
        migrations.AddField(
            model_name='article',
            name='img1',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='file1'),
        ),
        migrations.AddField(
            model_name='article',
            name='img2',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='file2'),
        ),
        migrations.AddField(
            model_name='article',
            name='part1',
            field=models.TextField(null=True, verbose_name='part1'),
        ),
        migrations.AddField(
            model_name='article',
            name='part2',
            field=models.TextField(blank=True, null=True, verbose_name='part1'),
        ),
        migrations.AddField(
            model_name='article',
            name='part3',
            field=models.TextField(blank=True, null=True, verbose_name='part1'),
        ),
    ]
