# Generated by Django 2.0.6 on 2018-06-17 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180616_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img1',
            field=models.FileField(blank=True, null=True, upload_to='%Y/%m/%d/', verbose_name='file1'),
        ),
        migrations.AlterField(
            model_name='article',
            name='img2',
            field=models.FileField(blank=True, null=True, upload_to='%Y/%m/%d/', verbose_name='file2'),
        ),
        migrations.AlterField(
            model_name='article',
            name='img3',
            field=models.FileField(blank=True, null=True, upload_to='%Y/%m/%d/', verbose_name='file3'),
        ),
    ]
