# Generated by Django 2.0.6 on 2018-06-17 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20180617_0331'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFile',
        ),
    ]
