# Generated by Django 2.0.6 on 2018-07-04 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20180704_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='put_on_top',
        ),
        migrations.RemoveField(
            model_name='article',
            name='views',
        ),
    ]
